Ensure php7.4 compatibility
splitbrain/php-cli pull request #16
Opened 2019-12-10 14:08 UTC by usox

Hi

Array and string offset access syntax with curly braces is deprecated in php 7.4 so I replaced it by strpos calls.
I also optimized the OptionTest a bit

2019-12-11 15:50 UTC, splitbrain requested changes
I believe, simply replacing the curly brackets with square brackets is faster than strpos. (I realize that this is a micro-optimization)

2019-12-11 15:56 UTC, usox commented
Hi

> I believe, simply replacing the curly brackets with square brackets is faster than strpos. 

I think so, too - it was my first approach. But I guess there are many people out there who don't know about the array-like access to char positions in a string, so I chose strpos.
If you prefer the array-like access, I will change the PR accordingly.

2019-12-12 06:36 UTC, usox commented
Done

2019-12-12 08:24 UTC, merged

2019-12-12 08:25 UTC, splitbrain commented
thanks